### ISSUE TITLE
Doesn't work with volumes on external host

### ISSUE THREAD

**Issue by pimuzzo** [istepanov/docker-dokuwiki#6]
Hi,
for example with my compose:
```
dokuwiki:
  container_name: dokuwiki
  image: istepanov/dokuwiki
  volumes:
    - dokuwiki_storage:/var/dokuwiki-storage
    - dokuwiki_plugins:/var/www/lib/plugins
  ports:
    - 80:80
```
If I mount volumes on an external host dokuwiki doesn't work.
